[tool.poetry]
name = "aiogram-widgets"
version = "0.1.0"
description = ""
authors = ["ggindinson <https://github.com/ggindinson>"]
readme = "README.md"
packages = [{include = "aiogram_widgets"}]

[tool.poetry.dependencies]
python = "^3.9"
aiogram = "^3.0.0b6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
